
package com.neteconomy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FinancialCrimeManager", targetNamespace = "http://neteconomy.com", wsdlLocation = "file:/C:/Users/subhash/Desktop/bobdocuments/AMLBankOfBarodaIndia.wsdl")
public class FinancialCrimeManager
    extends Service
{

    private final static URL FINANCIALCRIMEMANAGER_WSDL_LOCATION;
    private final static WebServiceException FINANCIALCRIMEMANAGER_EXCEPTION;
    private final static QName FINANCIALCRIMEMANAGER_QNAME = new QName("http://neteconomy.com", "FinancialCrimeManager");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
           // url = new URL("file:/C:/Users/subhash/Desktop/bobdocuments/AMLBankOfBarodaIndia.wsdl");
        	url = new URL("file:Files/AMLBankOfBarodaIndia.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FINANCIALCRIMEMANAGER_WSDL_LOCATION = url;
        FINANCIALCRIMEMANAGER_EXCEPTION = e;
    }

    public FinancialCrimeManager() {
        super(__getWsdlLocation(), FINANCIALCRIMEMANAGER_QNAME);
    }

    public FinancialCrimeManager(WebServiceFeature... features) {
        super(__getWsdlLocation(), FINANCIALCRIMEMANAGER_QNAME, features);
    }

    public FinancialCrimeManager(URL wsdlLocation) {
        super(wsdlLocation, FINANCIALCRIMEMANAGER_QNAME);
    }

    public FinancialCrimeManager(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FINANCIALCRIMEMANAGER_QNAME, features);
    }

    public FinancialCrimeManager(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FinancialCrimeManager(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FinancialCrimeManagerSoap
     */
    @WebEndpoint(name = "FinancialCrimeManagerSoap")
    public FinancialCrimeManagerSoap getFinancialCrimeManagerSoap() {
        return super.getPort(new QName("http://neteconomy.com", "FinancialCrimeManagerSoap"), FinancialCrimeManagerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FinancialCrimeManagerSoap
     */
    @WebEndpoint(name = "FinancialCrimeManagerSoap")
    public FinancialCrimeManagerSoap getFinancialCrimeManagerSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://neteconomy.com", "FinancialCrimeManagerSoap"), FinancialCrimeManagerSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FINANCIALCRIMEMANAGER_EXCEPTION!= null) {
            throw FINANCIALCRIMEMANAGER_EXCEPTION;
        }
        return FINANCIALCRIMEMANAGER_WSDL_LOCATION;
    }

}
