
package com.neteconomy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FinancialCrimeManagerSoap", targetNamespace = "http://neteconomy.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FinancialCrimeManagerSoap {


    /**
     * 
     * @param service
     * @return
     *     returns com.neteconomy.EraseResponse
     */
    @WebMethod(operationName = "SystemAdministrationGetAuthorities", action = "http://neteconomy.com/SystemAdministrationGetAuthorities")
    @WebResult(name = "SystemAdministrationGetAuthoritiesResult", targetNamespace = "http://neteconomy.com")
    @RequestWrapper(localName = "SystemAdministrationGetAuthorities", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.SystemAdministrationGetAuthorities")
    @ResponseWrapper(localName = "SystemAdministrationGetAuthoritiesResponse", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.SystemAdministrationGetAuthoritiesResponse")
    public EraseResponse systemAdministrationGetAuthorities(
        @WebParam(name = "Service", targetNamespace = "http://neteconomy.com")
        String service);

    /**
     * 
     * @param id
     * @return
     *     returns com.neteconomy.EraseResponse
     */
    @WebMethod(operationName = "SystemAdministrationStartJob", action = "http://neteconomy.com/SystemAdministrationStartJob")
    @WebResult(name = "SystemAdministrationStartJobResult", targetNamespace = "http://neteconomy.com")
    @RequestWrapper(localName = "SystemAdministrationStartJob", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.SystemAdministrationStartJob")
    @ResponseWrapper(localName = "SystemAdministrationStartJobResponse", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.SystemAdministrationStartJobResponse")
    public EraseResponse systemAdministrationStartJob(
        @WebParam(name = "ID", targetNamespace = "http://neteconomy.com")
        String id);

    /**
     * 
     * @param country
     * @param address
     * @param configuration
     * @param city
     * @param name
     * @param description
     * @param source
     * @param birthDate
     * @return
     *     returns com.neteconomy.EraseResponse
     */
    @WebMethod(operationName = "IndiaMatch", action = "http://neteconomy.com/IndiaMatch")
    @WebResult(name = "IndiaMatchResult", targetNamespace = "http://neteconomy.com")
    @RequestWrapper(localName = "IndiaMatch", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.IndiaMatch")
    @ResponseWrapper(localName = "IndiaMatchResponse", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.IndiaMatchResponse")
    public EraseResponse indiaMatch(
        @WebParam(name = "Configuration", targetNamespace = "http://neteconomy.com")
        String configuration,
        @WebParam(name = "Source", targetNamespace = "http://neteconomy.com")
        String source,
        @WebParam(name = "Name", targetNamespace = "http://neteconomy.com")
        String name,
        @WebParam(name = "Address", targetNamespace = "http://neteconomy.com")
        String address,
        @WebParam(name = "City", targetNamespace = "http://neteconomy.com")
        String city,
        @WebParam(name = "Country", targetNamespace = "http://neteconomy.com")
        String country,
        @WebParam(name = "BirthDate", targetNamespace = "http://neteconomy.com")
        String birthDate,
        @WebParam(name = "Description", targetNamespace = "http://neteconomy.com")
        String description);

    /**
     * 
     * @param configName
     * @param importFile
     * @param importText
     * @return
     *     returns com.neteconomy.EraseResponse
     */
    @WebMethod(operationName = "IndiaRunImport", action = "http://neteconomy.com/IndiaRunImport")
    @WebResult(name = "IndiaRunImportResult", targetNamespace = "http://neteconomy.com")
    @RequestWrapper(localName = "IndiaRunImport", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.IndiaRunImport")
    @ResponseWrapper(localName = "IndiaRunImportResponse", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.IndiaRunImportResponse")
    public EraseResponse indiaRunImport(
        @WebParam(name = "ConfigName", targetNamespace = "http://neteconomy.com")
        String configName,
        @WebParam(name = "ImportText", targetNamespace = "http://neteconomy.com")
        String importText,
        @WebParam(name = "ImportFile", targetNamespace = "http://neteconomy.com")
        String importFile);

    /**
     * 
     * @param businessObject
     * @return
     *     returns com.neteconomy.EraseResponse
     */
    @WebMethod(operationName = "IndiaImportExternalAlert", action = "http://neteconomy.com/IndiaImportExternalAlert")
    @WebResult(name = "IndiaImportExternalAlertResult", targetNamespace = "http://neteconomy.com")
    @RequestWrapper(localName = "IndiaImportExternalAlert", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.IndiaImportExternalAlert")
    @ResponseWrapper(localName = "IndiaImportExternalAlertResponse", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.IndiaImportExternalAlertResponse")
    public EraseResponse indiaImportExternalAlert(
        @WebParam(name = "businessObject", targetNamespace = "http://neteconomy.com")
        String businessObject);

    /**
     * 
     * @param country
     * @param address
     * @param configuration
     * @param city
     * @param name
     * @param description
     * @param source
     * @param birthDate
     * @return
     *     returns com.neteconomy.EraseResponse
     */
    @WebMethod(operationName = "IBUGIFTCITYMatch", action = "http://neteconomy.com/IBUGIFTCITYMatch")
    @WebResult(name = "IBUGIFTCITYMatchResult", targetNamespace = "http://neteconomy.com")
    @RequestWrapper(localName = "IBUGIFTCITYMatch", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.IBUGIFTCITYMatch")
    @ResponseWrapper(localName = "IBUGIFTCITYMatchResponse", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.IBUGIFTCITYMatchResponse")
    public EraseResponse ibugiftcityMatch(
        @WebParam(name = "Configuration", targetNamespace = "http://neteconomy.com")
        String configuration,
        @WebParam(name = "Source", targetNamespace = "http://neteconomy.com")
        String source,
        @WebParam(name = "Name", targetNamespace = "http://neteconomy.com")
        String name,
        @WebParam(name = "Address", targetNamespace = "http://neteconomy.com")
        String address,
        @WebParam(name = "City", targetNamespace = "http://neteconomy.com")
        String city,
        @WebParam(name = "Country", targetNamespace = "http://neteconomy.com")
        String country,
        @WebParam(name = "BirthDate", targetNamespace = "http://neteconomy.com")
        String birthDate,
        @WebParam(name = "Description", targetNamespace = "http://neteconomy.com")
        String description);

    /**
     * 
     * @param configName
     * @param importFile
     * @param importText
     * @return
     *     returns com.neteconomy.EraseResponse
     */
    @WebMethod(operationName = "IBUGIFTCITYRunImport", action = "http://neteconomy.com/IBUGIFTCITYRunImport")
    @WebResult(name = "IBUGIFTCITYRunImportResult", targetNamespace = "http://neteconomy.com")
    @RequestWrapper(localName = "IBUGIFTCITYRunImport", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.IBUGIFTCITYRunImport")
    @ResponseWrapper(localName = "IBUGIFTCITYRunImportResponse", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.IBUGIFTCITYRunImportResponse")
    public EraseResponse ibugiftcityRunImport(
        @WebParam(name = "ConfigName", targetNamespace = "http://neteconomy.com")
        String configName,
        @WebParam(name = "ImportText", targetNamespace = "http://neteconomy.com")
        String importText,
        @WebParam(name = "ImportFile", targetNamespace = "http://neteconomy.com")
        String importFile);

    /**
     * 
     * @param businessObject
     * @return
     *     returns com.neteconomy.EraseResponse
     */
    @WebMethod(operationName = "IBUGIFTCITYImportExternalAlert", action = "http://neteconomy.com/IBUGIFTCITYImportExternalAlert")
    @WebResult(name = "IBUGIFTCITYImportExternalAlertResult", targetNamespace = "http://neteconomy.com")
    @RequestWrapper(localName = "IBUGIFTCITYImportExternalAlert", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.IBUGIFTCITYImportExternalAlert")
    @ResponseWrapper(localName = "IBUGIFTCITYImportExternalAlertResponse", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.IBUGIFTCITYImportExternalAlertResponse")
    public EraseResponse ibugiftcityImportExternalAlert(
        @WebParam(name = "businessObject", targetNamespace = "http://neteconomy.com")
        String businessObject);

    /**
     * 
     * @param service
     * @return
     *     returns com.neteconomy.EraseResponse
     */
    @WebMethod(operationName = "GetAuthorities", action = "http://neteconomy.com/GetAuthorities")
    @WebResult(name = "GetAuthoritiesResult", targetNamespace = "http://neteconomy.com")
    @RequestWrapper(localName = "GetAuthorities", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.GetAuthorities")
    @ResponseWrapper(localName = "GetAuthoritiesResponse", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.GetAuthoritiesResponse")
    public EraseResponse getAuthorities(
        @WebParam(name = "Service", targetNamespace = "http://neteconomy.com")
        String service);

    /**
     * 
     * @param id
     * @return
     *     returns com.neteconomy.EraseResponse
     */
    @WebMethod(operationName = "StartJob", action = "http://neteconomy.com/StartJob")
    @WebResult(name = "StartJobResult", targetNamespace = "http://neteconomy.com")
    @RequestWrapper(localName = "StartJob", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.StartJob")
    @ResponseWrapper(localName = "StartJobResponse", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.StartJobResponse")
    public EraseResponse startJob(
        @WebParam(name = "ID", targetNamespace = "http://neteconomy.com")
        String id);

    /**
     * 
     * @param country
     * @param address
     * @param configuration
     * @param city
     * @param name
     * @param description
     * @param source
     * @param birthDate
     * @return
     *     returns com.neteconomy.EraseResponse
     */
    @WebMethod(operationName = "Match", action = "http://neteconomy.com/Match")
    @WebResult(name = "MatchResult", targetNamespace = "http://neteconomy.com")
    @RequestWrapper(localName = "Match", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.Match")
    @ResponseWrapper(localName = "MatchResponse", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.MatchResponse")
    public EraseResponse match(
        @WebParam(name = "Configuration", targetNamespace = "http://neteconomy.com")
        String configuration,
        @WebParam(name = "Source", targetNamespace = "http://neteconomy.com")
        String source,
        @WebParam(name = "Name", targetNamespace = "http://neteconomy.com")
        String name,
        @WebParam(name = "Address", targetNamespace = "http://neteconomy.com")
        String address,
        @WebParam(name = "City", targetNamespace = "http://neteconomy.com")
        String city,
        @WebParam(name = "Country", targetNamespace = "http://neteconomy.com")
        String country,
        @WebParam(name = "BirthDate", targetNamespace = "http://neteconomy.com")
        String birthDate,
        @WebParam(name = "Description", targetNamespace = "http://neteconomy.com")
        String description);

    /**
     * 
     * @param configName
     * @param importFile
     * @param importText
     * @return
     *     returns com.neteconomy.EraseResponse
     */
    @WebMethod(operationName = "RunImport", action = "http://neteconomy.com/RunImport")
    @WebResult(name = "RunImportResult", targetNamespace = "http://neteconomy.com")
    @RequestWrapper(localName = "RunImport", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.RunImport")
    @ResponseWrapper(localName = "RunImportResponse", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.RunImportResponse")
    public EraseResponse runImport(
        @WebParam(name = "ConfigName", targetNamespace = "http://neteconomy.com")
        String configName,
        @WebParam(name = "ImportText", targetNamespace = "http://neteconomy.com")
        String importText,
        @WebParam(name = "ImportFile", targetNamespace = "http://neteconomy.com")
        String importFile);

    /**
     * 
     * @param businessObject
     * @return
     *     returns com.neteconomy.EraseResponse
     */
    @WebMethod(operationName = "ImportExternalAlert", action = "http://neteconomy.com/ImportExternalAlert")
    @WebResult(name = "ImportExternalAlertResult", targetNamespace = "http://neteconomy.com")
    @RequestWrapper(localName = "ImportExternalAlert", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.ImportExternalAlert")
    @ResponseWrapper(localName = "ImportExternalAlertResponse", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.ImportExternalAlertResponse")
    public EraseResponse importExternalAlert(
        @WebParam(name = "businessObject", targetNamespace = "http://neteconomy.com")
        String businessObject);

    /**
     * 
     * @return
     *     returns com.neteconomy.EraseResponse
     */
    @WebMethod(operationName = "Execute", action = "http://neteconomy.com/Execute")
    @WebResult(name = "ExecuteResult", targetNamespace = "http://neteconomy.com")
    @RequestWrapper(localName = "Execute", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.Execute")
    @ResponseWrapper(localName = "ExecuteResponse", targetNamespace = "http://neteconomy.com", className = "com.neteconomy.ExecuteResponse")
    public EraseResponse execute();

}
