
package com.infosys.ci.fiusb.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FIUsbWebService", targetNamespace = "http://webservice.fiusb.ci.infosys.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FIUsbWebService {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.infosys.ci.fiusb.webservice.ExecuteServiceResponse
     */
    @WebMethod
    @WebResult(name = "executeServiceResponse", targetNamespace = "http://webservice.fiusb.ci.infosys.com", partName = "parameters")
    public ExecuteServiceResponse executeService(
        @WebParam(name = "executeService", targetNamespace = "http://webservice.fiusb.ci.infosys.com", partName = "parameters")
        ExecuteService parameters);

}
