package com.infosys.ci.fiusb.webservice;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.bs.themebridge.token.util.ConfigurationUtil;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "FIUsbWebServiceService", targetNamespace = "http://webservice.fiusb.ci.infosys.com", wsdlLocation = "http://localhost:8088/mockFIUsbWebServiceSoapBinding?WSDL")
public class FIUsbWebServiceService extends Service {

	private final static URL FIUSBWEBSERVICESERVICE_WSDL_LOCATION;
	private final static WebServiceException FIUSBWEBSERVICESERVICE_EXCEPTION;
	private final static QName FIUSBWEBSERVICESERVICE_QNAME = new QName(
			"http://webservice.fiusb.ci.infosys.com", "FIUsbWebServiceService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL(ConfigurationUtil.getValueFromKey("FIUsbWebService"));
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		FIUSBWEBSERVICESERVICE_WSDL_LOCATION = url;
		FIUSBWEBSERVICESERVICE_EXCEPTION = e;
	}

	public FIUsbWebServiceService() {
		super(__getWsdlLocation(), FIUSBWEBSERVICESERVICE_QNAME);
	}

 
	public FIUsbWebServiceService(URL wsdlLocation) {
		super(wsdlLocation, FIUSBWEBSERVICESERVICE_QNAME);
	}
 
	public FIUsbWebServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}
 

	/**
	 * 
	 * @return returns FIUsbWebService
	 */
	@WebEndpoint(name = "FIUsbWebService")
	public FIUsbWebService getFIUsbWebService() {
		return super.getPort(new QName(
				"http://webservice.fiusb.ci.infosys.com", "FIUsbWebService"),
				FIUsbWebService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns FIUsbWebService
	 */
	@WebEndpoint(name = "FIUsbWebService")
	public FIUsbWebService getFIUsbWebService(WebServiceFeature... features) {
		return super.getPort(new QName(
				"http://webservice.fiusb.ci.infosys.com", "FIUsbWebService"),
				FIUsbWebService.class, features);
	}

	private static URL __getWsdlLocation() {
		if (FIUSBWEBSERVICESERVICE_EXCEPTION != null) {
			throw FIUSBWEBSERVICESERVICE_EXCEPTION;
		}
		return FIUSBWEBSERVICESERVICE_WSDL_LOCATION;
	}

}
